### ISSUE TITLE
Stable documentation not found

### ISSUE THREAD

**Issue by dermesser** [JuliaPhysics/PhysicalOptics.jl#11]
While browsing your project, I noticed that the stable documentation is not available: github pages delivers a 404 error. The dev documentation works (and it seems you don't have much there, anyway), but I wanted to notify regardless -- just in case it is not intentional :-)

**Comment by roflmaostc** [comment]
There is simply no stable release yet.

And it won't be coming soon since I want to rewrite this package mostly.

**Comment by dermesser** [comment]
I see - apologies then for the false alarm.

**Comment by roflmaostc** [comment]
It's OK :D

I try to get it reworking maybe next year
